dependencies:
  - gunicorn=20.1.0 # old value=20.0.4  # https://github.com/benoitc/gunicorn]
  - psycopg2==2.8.6  # https://github.com/psycopg/psycopg2
  - pip:
    - django_compressor==2.4.1
    - django-storages[boto3]==1.11.1  # https://github.com/jschneier/django-storages
    - django-anymail[mailgun]==8.2  # https://github.com/anymail/django-anymail
